### PR TITLE
New layout

### PR DESCRIPTION
**Pull request by aalvarado**
Please review.

### CODE REVIEW

**Comment by aalvarado** [comment]
Screen Shot 2013-04-12 at 5 02 18 PM
preview

**Comment by EnriqueVidal** [comment]
It looks good I just have a couple of observations:
1. The `<pre>` don't seem to be monospaced, I looked at it  and the first font is Monaco, which mean they should be, so I'm not sure if the browser is not redering them correctly, we could use Source Code Pro from Adobe from google fonts though.
2. There is very little difference between the headings `<h1>..<h4>` in size and font style.
3. Mentions `<blockquote>` look a bit weird too, thay may be because markdown is interpreting them as `<blockquote><p> ... </p></blockquote>`, we may need styles for `blockquote p {}`
4. We still need to address the problem with alignment and the wasted white space on the right.

White space and headings

Code snippets

**Comment by aalvarado** [comment]
> It looks good I just have a couple of observations:

Thanks!

> 1. The `<pre>` don't seem to be monospaced, I looked at it and the first font is Monaco, which mean they should be, so I'm not sure if the browser is not redering them correctly, we could use Source Code Pro from Adobe from google fonts though.

yeah it doesn't seem like that's included from css lib, will definitely change it

> 1. There is very little difference between the headings `<h1>..<h4>` in size and font style.
>    Mentions `<blockquote>` look a bit weird too, thay may be because markdown is interpreting them as `<blockquote><p> ... </p></blockquote>`, we may need styles for blockquote p {}

That's weird, .5em on average means that there's at least around 8 pixels of difference between each heading, Plus those are copied from: http://websymphony.net/almost-flat-ui/ which I think css library makers have a bit more knowledge regarding font sizes. If you want to suggest a style that you think might well suited for font sizes I would be glad if you point me to it.

yeah, the blockquote could be improved.

```
h1, h2, h3, h4, h5, h6 {
  line-height: 1.4;
}

h1{
  font-size: 2.75em;
}
h2 {
  font-size: 2.3125em;
}
h3 {
  font-size: 1.6875em;
}
h4 {
  font-size: 1.4375em;
}
h5 {
  font-size: 1.125em;
}
h6 {
  font-size: 1em;
}
```

> 1. We still need to address the problem with alignment and the wasted white space on the right.

It would be cool if you could point out exactly were the alignment problem is. As for "wasted" space on the right we could toggle, or flow the text to the left, but instead of having it look better I think it would look slightly sloppy. Don't fear the whitespace. Look at the https://github.com/blog for example, they have a menu on the left that only appears on the top, inner content is capped at 620~px, which is not what I'm using ( 640px ), which has even more space for content. 

Thanks for your input.

**Comment by aalvarado** [comment]
Fixed most of the comments you made @EnriqueVidal . I think it is safe to merge.

**Pull request merged**
