### PR TITLE
Add acl9

### PR DESCRIPTION
**Pull request by javierg**
ready to be merge...

needs more bitches!

### CODE REVIEW

**Comment by marioBonales** [comment]
As I was commenting with @EnriqueVidal, we probably should add roles based on the github profile user, A council user should be a user that has at least one public ruby repository.

**Comment by EnriqueVidal** [comment]
@marioBonales You mean keeping `acl9` but base the role granting part to the the users repos?.

Also, if I were to give them roles based on their github profile I would look if they are members of the rubytij org instead, but for this to work we need to not give access to everyone, and do a more thorough check before adding new owners.

**Comment by EnriqueVidal** [comment]
My last commit puts this branch up to date, I noticed some changes were left out I wonder if @javierg left them out intentionally the missing parts include:
1. The use of `acl9`
2. The `Role` specs

I'll wait for @marioBonales update on how to do the RBAC before merging.

**Comment by javierg** [comment]
Did not use it because this only adds the basic framework for using it. We have to set the roles rules before, and that is why I didn't write the roles specs, once this is merged we can do all the work of setting those rules.

**Pull request merged**
